"use client"
import Navigation from './components/Navigation/page'
import './globals.css'

export const pageMetadata = {
  title: 'Metasurance.js',
  description: 'Generated by Metasurance',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

